# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex07', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='created',
            field=models.DateTimeField(default='2017-04-11 11:20:12.159943'),
        ),
        migrations.AddField(
            model_name='movies',
            name='updated',
            field=models.DateTimeField(default='2017-04-11 11:20:12.160004'),
        ),
    ]
